name: palmfarm
description: "palmfrarm client"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  get_it: ^7.6.4
  injectable: 2.2.0
  gap: ^3.0.1
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1
  rxdart: ^0.27.7
  fluttertoast: ^8.2.4

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_reactive_ble: ^5.3.1
  ubuntu_widgets: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  freezed: ^2.4.5
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  injectable_generator:
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/assets/
